name: core
apiVersion: v1
version: 2.4.500020230629
appVersion: jenkins-nv-build-fleet-4857
description: Helm chart for NeuVector's core services
home: https://neuvector.com
icon: https://avatars2.githubusercontent.com/u/19367275?s=200&v=4
maintainers:
  - name: becitsthere
    email: support@neuvector.com
engine: gotpl
