# Default values for neuvector.
# This is a YAML-formatted file.
# Declare variables to be passed into the templates.

openshift: false

registry: 709825985650.dkr.ecr.us-east-1.amazonaws.com
oem:
imagePullSecrets:
psp: false
rbac: true # required for rancher authentication
serviceAccount: default
leastPrivilege: false
global: # required for rancher authentication (https://<Rancher_URL>/)
  cattle:
    url:

internal: # enable when cert-manager is installed for the internal certificates
  certmanager:
    enabled: false
    secretname: neuvector-internal

controller:
  # If false, controller will not be installed
  enabled: true
  annotations: {}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  image:
    repository: suse/neuvector-csp-billing-adapter-llc/controller
    tag: jenkins-nv-build-fleet-4857
    hash: sha256:c9cdedf0908b06148b5a062b27d184add434bcce831f54d7b692e35d56c2e006
  replicas: 3
  disruptionbudget: 0
  schedulerName:
  priorityClassName:
  podLabels: {}
  podAnnotations: {}
  env: []
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - neuvector-controller-pod
          topologyKey: "kubernetes.io/hostname"
  tolerations: []
  nodeSelector: {}
    # key1: value1
    # key2: value2
  apisvc:
    type:
    annotations: {}
    # OpenShift Route configuration
    # Controller supports HTTPS only, so edge termination not supported
    route:
      enabled: false
      termination: passthrough
      host:
      tls:
        #certificate: |
        #  -----BEGIN CERTIFICATE-----
        #  -----END CERTIFICATE-----
        #caCertificate: |
        #  -----BEGIN CERTIFICATE-----
        #  -----END CERTIFICATE-----
        #destinationCACertificate: |
        #  -----BEGIN CERTIFICATE-----
        #  -----END CERTIFICATE-----
        #key: |
        #  -----BEGIN PRIVATE KEY-----
        #  -----END PRIVATE KEY-----
  ranchersso: # required for rancher authentication
    enabled: false
  pvc:
    enabled: false
    existingClaim: false
    accessModes:
      - ReadWriteMany
    storageClass:
    capacity:
  azureFileShare:
    enabled: false
    secretName:
    shareName:
  certificate:
    secret:
    keyFile: tls.key
    pemFile: tls.pem
  internal: # this is used for internal communication. Please use the SAME CA for all the components (controller, scanner, adapter and enforcer)
    certificate:
      secret: neuvector-internal
      keyFile: tls.key
      pemFile: tls.crt
      caFile: ca.crt # must be the same CA for all internal.
  federation:
    mastersvc:
      type:
      # Federation Master Ingress
      ingress:
        enabled: false
        host:  # MUST be set, if ingress is enabled
        ingressClassName: ""
        path: "/"  # or this could be "/api", but might need "rewrite-target" annotation
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          # ingress.kubernetes.io/rewrite-target: /
        tls: false
        secretName:
      annotations: {}
      # OpenShift Route configuration
      # Controller supports HTTPS only, so edge termination not supported
      route:
        enabled: false
        termination: passthrough
        host:
        tls:
          #certificate: |
          #  -----BEGIN CERTIFICATE-----
          #  -----END CERTIFICATE-----
          #caCertificate: |
          #  -----BEGIN CERTIFICATE-----
          #  -----END CERTIFICATE-----
          #destinationCACertificate: |
          #  -----BEGIN CERTIFICATE-----
          #  -----END CERTIFICATE-----
          #key: |
          #  -----BEGIN PRIVATE KEY-----
          #  -----END PRIVATE KEY-----
    managedsvc:
      type:
      # Federation Managed Ingress
      ingress:
        enabled: false
        host:  # MUST be set, if ingress is enabled
        ingressClassName: ""
        path: "/"  # or this could be "/api", but might need "rewrite-target" annotation
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          # ingress.kubernetes.io/rewrite-target: /
        tls: false
        secretName:
      annotations: {}
      # OpenShift Route configuration
      # Controller supports HTTPS only, so edge termination not supported
      route:
        enabled: false
        termination: passthrough
        host:
        tls:
          #certificate: |
          #  -----BEGIN CERTIFICATE-----
          #  -----END CERTIFICATE-----
          #caCertificate: |
          #  -----BEGIN CERTIFICATE-----
          #  -----END CERTIFICATE-----
          #destinationCACertificate: |
          #  -----BEGIN CERTIFICATE-----
          #  -----END CERTIFICATE-----
          #key: |
          #  -----BEGIN PRIVATE KEY-----
          #  -----END PRIVATE KEY-----
  ingress:
    enabled: false
    host:  # MUST be set, if ingress is enabled
    ingressClassName: ""
    path: "/"  # or this could be "/api", but might need "rewrite-target" annotation
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      # ingress.kubernetes.io/rewrite-target: /
    tls: false
    secretName:
  resources: {}
    # limits:
    #   cpu: 400m
    #   memory: 2792Mi
    # requests:
    #   cpu: 100m
    #   memory: 2280Mi
  configmap:
    enabled: false
    data:
      # passwordprofileinitcfg.yaml: |
      #  ...
      # roleinitcfg.yaml: |
      #  ...
      # ldapinitcfg.yaml: |
      #  ...
      # oidcinitcfg.yaml: |
      # ...
      # samlinitcfg.yaml: |
      # ...
      # sysinitcfg.yaml: |
      # ...
      # userinitcfg.yaml: |
      # ...
  secret:
    # NOTE: files defined here have preferrence over the ones defined in the configmap section
    enabled: false
    data: {}
      # passwordprofileinitcfg.yaml: |
      #  ...
      # roleinitcfg.yaml: |
      #  ...
      # ldapinitcfg.yaml:
      #   directory: OpenLDAP
      #   ...
      # oidcinitcfg.yaml:
      #   Issuer: https://...
      #   ...
      # samlinitcfg.yaml:
      #   ...
      # sysinitcfg.yaml:
      #   ...
      # userinitcfg.yaml:
      #   ...

enforcer:
  # If false, enforcer will not be installed
  enabled: true
  image:
    repository: suse/neuvector-csp-billing-adapter-llc/enforcer
    tag: jenkins-nv-build-fleet-4857
    hash: sha256:c65768f9a11277b8351642b28ce7754ca08c02d22dd6c0b7991d2ce7c4a648da
  updateStrategy:
    type: RollingUpdate
  priorityClassName:
  podLabels: {}
  podAnnotations: {}
  env: []
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
  resources: {}
    # limits:
    #   cpu: 400m
    #   memory: 2792Mi
    # requests:
    #   cpu: 100m
    #   memory: 2280Mi
  internal: # this is used for internal communication. Please use the SAME CA for all the components (controller, scanner, adapter and enforcer)
    certificate:
      secret: neuvector-internal
      keyFile: tls.key
      pemFile: tls.crt
      caFile: ca.crt # must be the same CA for all internal.

manager:
  # If false, manager will not be installed
  enabled: true
  image:
    repository: suse/neuvector-csp-billing-adapter-llc/manager
    tag: jenkins-nv-build-manager-3731
    hash: sha256:9a5d99de18ed21f0e3d942d7881a7bc30de662ed9a40d6d73c7b830a8299ca52
  priorityClassName:
  env:
    ssl: true
    envs: []
#      - name: CUSTOM_PAGE_HEADER_COLOR
#        value: "#FFFFFF"
#      - name: CUSTOM_PAGE_FOOTER_COLOR
#        value: "#FFFFFF"
  svc:
    type: NodePort # should be set to - ClusterIP
    loadBalancerIP:
    annotations: {}
      # azure
      # service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      # service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "apps-subnet"
  # OpenShift Route configuration
  # Make sure manager env ssl is false for edge termination
  route:
    enabled: true
    termination: passthrough
    host:
    tls:
      #certificate: |
      #  -----BEGIN CERTIFICATE-----
      #  -----END CERTIFICATE-----
      #caCertificate: |
      #  -----BEGIN CERTIFICATE-----
      #  -----END CERTIFICATE-----
      #destinationCACertificate: |
      #  -----BEGIN CERTIFICATE-----
      #  -----END CERTIFICATE-----
      #key: |
      #  -----BEGIN PRIVATE KEY-----
      #  -----END PRIVATE KEY-----
  certificate:
    secret:
    keyFile: tls.key
    pemFile: tls.pem
  ingress:
    enabled: false
    host:  # MUST be set, if ingress is enabled
    ingressClassName: ""
    path: "/"
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      # kubernetes.io/ingress.class: my-nginx
      # nginx.ingress.kubernetes.io/whitelist-source-range: "1.1.1.1"
      # nginx.ingress.kubernetes.io/rewrite-target: /
      # nginx.ingress.kubernetes.io/enable-rewrite-log: "true"
      # only for end-to-end tls conf - ingress-nginx accepts backend self-signed cert
    tls: false
    secretName:  # my-tls-secret
  resources: {}
    # limits:
    #   cpu: 400m
    #   memory: 2792Mi
    # requests:
    #   cpu: 100m
    #   memory: 2280Mi
  affinity: {}
  podLabels: {}
  podAnnotations: {}
  tolerations: []
  nodeSelector: {}
    # key1: value1
    # key2: value2
  runAsUser:  # MUST be set for Rancher hardened cluster

cve:
  adapter:
    enabled: false
    image:
      repository: suse/neuvector-csp-billing-adapter-llc/registry-adapter
      tag: jenkins-nv-build-adapter-14
      hash: sha256:ed8b5c14371fa0394c3f2c54154ca4864909b4ef09dff11f05fd4d7b726bf17b
    priorityClassName:
    resources: {}
      # limits:
      #   cpu: 400m
      #   memory: 512Mi
      # requests:
      #   cpu: 100m
      #   memory: 1024Mi
    affinity: {}
    podLabels: {}
    podAnnotations: {}
    env: []
    tolerations: []
    nodeSelector: {}
      # key1: value1
      # key2: value2
    runAsUser:  # MUST be set for Rancher hardened cluster
    certificate:
      secret:
      keyFile: tls.key
      pemFile: tls.pem
    harbor:
      protocol: https
      secretName:
    svc:
      type: NodePort # should be set to - ClusterIP
      loadBalancerIP:
      annotations: {}
        # azure
        # service.beta.kubernetes.io/azure-load-balancer-internal: "true"
        # service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "apps-subnet"
    # OpenShift Route configuration
    route:
      enabled: true
      termination: passthrough
      host:
      tls:
        #certificate: |
        #  -----BEGIN CERTIFICATE-----
        #  -----END CERTIFICATE-----
        #caCertificate: |
        #  -----BEGIN CERTIFICATE-----
        #  -----END CERTIFICATE-----
        #destinationCACertificate: |
        #  -----BEGIN CERTIFICATE-----
        #  -----END CERTIFICATE-----
        #key: |
        #  -----BEGIN PRIVATE KEY-----
        #  -----END PRIVATE KEY-----
    ingress:
      enabled: false
      host:  # MUST be set, if ingress is enabled
      ingressClassName: ""
      path: "/"
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        # kubernetes.io/ingress.class: my-nginx
        # nginx.ingress.kubernetes.io/whitelist-source-range: "1.1.1.1"
        # nginx.ingress.kubernetes.io/rewrite-target: /
        # nginx.ingress.kubernetes.io/enable-rewrite-log: "true"
        # only for end-to-end tls conf - ingress-nginx accepts backend self-signed cert
      tls: false
      secretName:  # my-tls-secret
    internal: # this is used for internal communication. Please use the SAME CA for all the components (controller, scanner, adapter and enforcer)
      certificate:
        secret: neuvector-internal
        keyFile: tls.key
        pemFile: tls.crt
        caFile: ca.crt # must be the same CA for all internal.
  updater:
    # If false, cve updater will not be installed
    enabled: true
    secure: false
    image:
      repository: suse/neuvector-csp-billing-adapter-llc/updater
      tag: 5_20230622
      hash: sha256:31c7c4b46e0f846059568939c797af8db9beb140b7504fddc6fcc5b81e4bb80b
    schedule: "0 0 * * *"
    priorityClassName:
    podLabels: {}
    podAnnotations: {}
    nodeSelector: {}
      # key1: value1
      # key2: value2
    runAsUser:  # MUST be set for Rancher hardened cluster
  scanner:
    enabled: true
    replicas: 3
    dockerPath: ""
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
    image:
      repository: suse/neuvector-csp-billing-adapter-llc/scanner
      tag: 5_20230622
      hash: sha256:dcf41f155b9209f859f2d0a1e13a4fb93ef4a62252592e5f24ba04b9a56e9558
    priorityClassName:
    resources: {}
      # limits:
      #   cpu: 400m
      #   memory: 2792Mi
      # requests:
      #   cpu: 100m
      #   memory: 2280Mi
    affinity: {}
    podLabels: {}
    podAnnotations: {}
    env: []
    tolerations: []
    nodeSelector: {}
      # key1: value1
      # key2: value2
    runAsUser:  # MUST be set for Rancher hardened cluster
    internal: # this is used for internal communication. Please use the SAME CA for all the components (controller, scanner, adapter and enforcer)
      certificate:
        secret: neuvector-internal
        keyFile: tls.key
        pemFile: tls.crt
        caFile: ca.crt # must be the same CA for all internal.

docker:
  path: /var/run/docker.sock

resources: {}
  # limits:
  #   cpu: 400m
  #   memory: 2792Mi
  # requests:
  #   cpu: 100m
  #   memory: 2280Mi

k3s:
  enabled: false
  runtimePath: /run/k3s/containerd/containerd.sock

bottlerocket:
  enabled: false
  runtimePath: /run/dockershim.sock

containerd:
  enabled: true
  path: /var/run/containerd/containerd.sock

crio:
  enabled: false
  path: /var/run/crio/crio.sock

admissionwebhook:
  type: ClusterIP

crdwebhook:
  enabled: true
  type: ClusterIP

awsbilling:
  enabled: true
  accountNumber: ""
  roleName: ""
  serviceAccount: csp
  annotations: {}
  imagePullSecrets:
  image:
    repository: suse/neuvector-csp-billing-adapter-llc/csp-billing-adapter
    tag: 0.3.0.17.2
    hash: sha256:b48ebec76b2e3dd4962eb70a9ed183ff61506fbd1644e5eaef9fdf28145183ec
    imagePullPolicy: IfNotPresent

gpcbilling:
  enabled: false
  accountNumber: ""
  roleName: ""
  serviceAccount: csp
  annotations: {}
  imagePullSecrets:
  image:
    repository: neuvector/neuvector-csp-adapter
    tag: 1.0.0
    imagePullPolicy: IfNotPresent

microsoftbilling:
  enabled: false
  accountNumber: ""
  roleName: ""
  serviceAccount: csp
  annotations: {}
  imagePullSecrets:
  image:
    repository: neuvector/neuvector-csp-adapter
    tag: 1.0.0
    imagePullPolicy: IfNotPresent
